"""empty message

Revision ID: 313af75c1207
Revises: 6dd701c108f6
Create Date: 2022-09-26 00:29:07.438995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313af75c1207'
down_revision = '6dd701c108f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todoslists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'todoslists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todoslists')
    # ### end Alembic commands ###
