"""empty message

Revision ID: 550d911d7dac
Revises: 313af75c1207
Create Date: 2022-09-26 00:33:26.715710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550d911d7dac'
down_revision = '313af75c1207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoslists', sa.Column('todo_category', sa.String(), nullable=False))
    op.drop_column('todoslists', 'todo_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoslists', sa.Column('todo_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todoslists', 'todo_category')
    # ### end Alembic commands ###
