"""empty message

Revision ID: ffae3d529316
Revises: e2d6002c0f3b
Create Date: 2022-09-27 00:10:00.460011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffae3d529316'
down_revision = 'e2d6002c0f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoslists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('update todoslists set completed = false')
    op.alter_column('todoslists', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todoslists', 'completed')
    # ### end Alembic commands ###
